### ISSUE TITLE
This is great + upsert request etc.

### ISSUE THREAD

**Issue by nevf** [YuriSolovyov/Dexie-mongoify#1]
@YuriSolovyov I just found mongoify yesterday and have already put it to good use. Many thanks for creating this. The Dexie site needs a list of add-ons, which I'll suggest to them.

One thing I'd like is the ability to use the Mongodb `upsert` option in `update()` I've done a crude implementation in my own code which I can show you, if it's of interest.

It would also be good if functions returned the same values as the native mongo driver. For example `update` returned `WriteResult`

I'm using MongoDb on the server in a Node.js app and have made a start using Dexie.js in the Browser. mongoify will certainly be a most welcome help in unifying code for my Web app Clibu, http://clibu.com

Could you please write some Wiki content on how mongoify uses indexes. I've had a quick look through the code, but it needs more than that.

We desperately need a unified database api and functionality across Server & Browser, as right now it's a mess. Interestingly there is an job advertisement on the MongoDb site for someone to work on a Browser version of Mongodb!

We have IndexedDB in the Browser which is complex to use, but has a good range of features (secondary indexes, sub-document indexes etc). And Dexie is great.

And for an in-process database on Node.js we really only have leveldb which sadly lacks secondary indexes, sub-document indexes, composite keys etc. The are good wrappers such as levelup, linvodb3 https://github.com/Ivshti/linvodb3 which provides a mongodb api, but currently uses in-memory indexes.

**Comment by YurySolovyov** [comment]
> Could you please write some Wiki content on how mongoify uses indexes. I've had a quick look through the code, but it needs more than that.

ATM use of indexes is quite limited, they are used only in simpliest cases like fetching items by id or indexed field. Anything else falls back to full scan with filtering in JS-land. This was good enough for me back then, but it looks like it worth revisiting.

> One thing I'd like is the ability to use the Mongodb upsert option in update() I've done a crude implementation in my own code which I can show you, if it's of interest.

Sure, I'll take a look at adding it, your implementation on gist is appreticated too.

> It would also be good if functions returned the same values as the native mongo driver. For example update returned WriteResult

Can you point me to docs or wiki explaining this?

**Comment by nevf** [comment]
@YuriSolovyov Thanks for the extra info on index use. Using indexes whenever possible is definitely a big plus,

This is my crude upsert code. I'm only interested in using `$set` at present so that's all it checks for.

```
db[ table ].update( query, update ).then(
    function( result ){
        // result - count of doc's updated.
        if ( result === 0 && options && options.upsert ){
            // rem: We need to combine `query + update` to make the doc to insert.
            //      ex. { what: "tips", hover: false } <- query { what: "tips" }, update { hover: false }
            var doc = _.assign( query, update.$set ? update.$set : update )
            db[ table ].insert( doc ).then(
                function( result ){
                    resolve( { "nMatched" : 0, "nUpserted" : 1, "nModified" : 0 } )     // WriteResult same as MongoDb
                },
                function( error ){
                    reject( error )
                }
            )
        }else
            resolve( { "nMatched" : result, "nUpserted" : 0, "nModified" : result } ) 
    },
    function( error ){
            ...
    }
```

The MongoDB Native Node.js docs are at: http://mongodb.github.io/node-mongodb-native/2.1/api/ You can find the `collection typedefs` such as `updateWriteOpResult` there. ex. http://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html#~updateWriteOpResult

**Comment by YurySolovyov** [comment]
@nevf Status update: I'm currently working on some benchmarking automation and moving existing tests to karma so I can spin up a CI and monitor performance and/or behavior better.

Next I'll take a look at `upsert` implementation and how can I make better use of indexes and Dexie native methods.

**Comment by YurySolovyov** [comment]
Started #3 for upsert option.

**Comment by nevf** [comment]
@YuriSolovyov Thanks, I look forward to see mongoify continue to develop and improve.

**Comment by nevf** [comment]
@YuriSolovyov I asked if a Dexie page could be created for addons and it has been. See:  https://github.com/dfahlander/Dexie.js/wiki/DerivedWork Hopefully more people will find mongoify now.

**Comment by YurySolovyov** [comment]
Thanks, good to know.

**Comment by YurySolovyov** [comment]
I added upsert and return types for API calls and released new version, so I'm closing this.
