### ISSUE TITLE
Add Bower file configuration

### ISSUE THREAD

**Issue by felipedelpozo** [YuriSolovyov/Dexie-mongoify#11]
Please, add integration with bower.

**Comment by YurySolovyov** [comment]
@felipedelpozo how about publishing it to npm ? I personally don't like bower

**Comment by felipedelpozo** [comment]
Thanks for your reply, but the project uses bower.

**Comment by YurySolovyov** [comment]
@felipedelpozo can't bower use npm as source?

**Comment by YurySolovyov** [comment]
or you can make bower point to this repo 

```
bower install git://github.com/user/package.git
```

**Comment by felipedelpozo** [comment]
I did not know! thank you very much

**Comment by YurySolovyov** [comment]
Thanks for the interest, I'll add it to npm to make it more accessible and discoverable.
